[DERCBOT-753] Dev
CreditMutuelArkea/tock-docker pull request #2
Opened 2023-11-06 08:59 UTC by assouktim

Init new tock module : llm python core

2023-11-07 15:46 UTC, Benvii requested changes

2023-11-07 15:46 UTC, Benvii commented on pom.xml
> +                <artifactId>tock-llm-python-core</artifactId>
Rename it `tock-llm-orchestrator` or maybe ` tock-llm-orchestrator-server` as we will have a client and server package.

2023-11-07 15:46 UTC, Benvii commented on docker-compose-llm-python-core.yml
> +
Ok for this simple docker-compose file that only handle the llm orchestration server. But it would be create to have a `docker-compose-bot-rag.yml` file with all Tock stack and the LLM orchestrator.

2023-11-07 15:46 UTC, Benvii commented on docker-compose-llm-python-core.yml
> +  llm_python_core:
Rename it ` llm-orchestrator-server`

2023-11-07 15:46 UTC, Benvii commented on llm-python-core/Dockerfile
> +RUN pip install -r requirements.txt
Prefer using poetry : https://medium.com/@albertazzir/blazing-fast-python-docker-builds-with-poetry-a78a66f5aed0

2023-11-09 16:26 UTC, assouktim commented
PR remplacé par : https://github.com/CreditMutuelArkea/tock-docker/pull/2

2023-11-15 11:29 UTC, closed without merging